USE [master]
GO

/****** Object:  Database [Lista6]    Script Date: 13.12.2020 15:51:38 ******/
CREATE DATABASE [Lista6]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Lista6', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.ASDF\MSSQL\DATA\Lista6.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Lista6_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.ASDF\MSSQL\DATA\Lista6_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Lista6].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Lista6] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Lista6] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Lista6] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Lista6] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Lista6] SET ARITHABORT OFF 
GO

ALTER DATABASE [Lista6] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Lista6] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Lista6] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Lista6] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Lista6] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Lista6] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Lista6] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Lista6] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Lista6] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Lista6] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Lista6] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Lista6] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Lista6] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Lista6] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Lista6] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Lista6] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Lista6] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Lista6] SET RECOVERY FULL 
GO

ALTER DATABASE [Lista6] SET  MULTI_USER 
GO

ALTER DATABASE [Lista6] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Lista6] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Lista6] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Lista6] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Lista6] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Lista6] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Lista6] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Lista6] SET  READ_WRITE 
GO

